export const BUILDING_ITEMS = [
  {
    id: 1,
    name: "Dangote Cement",
    category: "Cement",
    unit: "Bags",
  },
  {
    id: 2,
    name: "Elephant Cement",
    category: "Cement",
    unit: "Bags",
  },
  {
    id: 3,
    name: "Water Shield Cement",
    category: "Cement",
    unit: "Bags",
  },
  {
    id: 4,
    name: "LAFARGE Cement",
    category: "Cement",
    unit: "Bags",
  },
  {
    id: 5,
    name: "POP Cement (Smooth)",
    category: "POP",
    unit: "Bags",
  },
  {
    id: 6,
    name: "POP Cement (Phoenix)",
    category: "POP",
    unit: "Bags",
  },
  {
    id: 7,
    name: "Top Bond",
    category: "Adhesives",
    unit: "Bags",
  },
  {
    id: 8,
    name: "Emulsion Paint",
    category: "Paint",
    unit: "Buckets",
  },
  {
    id: 9,
    name: "Gloss Paint",
    category: "Paint",
    unit: "Buckets",
  },
  {
    id: 10,
    name: "Satin Paint",
    category: "Paint",
    unit: "Buckets",
  },
  {
    id: 11,
    name: "Asbestos Plain",
    category: "Roofing Sheet",
    unit: "Pieces",
  },
  {
    id: 12,
    name: "Asbestos Design",
    category: "Roofing Sheet",
    unit: "Pieces",
  },
  {
    id: 13,
    name: "Litespan (Solo)",
    category: "Roofing Sheet",
    unit: "Pieces",
  },
  {
    id: 14,
    name: "Tierod",
    category: "Roofing Sheet",
    unit: "Pieces",
  },
  {
    id: 15,
    name: "Facial Board",
    category: "Roofing Sheet",
    unit: "Pieces",
  },
  {
    id: 16,
    name: "Slate",
    category: "Roofing",
    unit: "Pieces",
  },
  {
    id: 17,
    name: "MDF Board",
    category: "Boards",
    unit: "Sheets",
  },
  {
    id: 18,
    name: "HDF Board",
    category: "Boards",
    unit: "Sheets",
  },
  {
    id: 19,
    name: "Back Cover",
    category: "Boards",
    unit: "Sheets",
  },
  {
    id: 20,
    name: "Hard Board",
    category: "Boards",
    unit: "Sheets",
  },
  {
    id: 21,
    name: "Fillas",
    category: "POP",
    unit: "Bundle",
  },
  {
    id: 22,
    name: "Keys",
    category: "Accessories",
    unit: "Pieces",
  },
  {
    id: 23,
    name: "Door handles",
    category: "Accessories",
    unit: "Pieces",
  },
];